### ISSUE TITLE
How to deal with root partition full on arch installation media?

### ISSUE THREAD

**Issue by oz123** [szorfein/getch#5]
Maybe the wrong tree to bark at ... I recently tried using arch linux media to use this installer.
The installer of arch now completely copies itself to the RAM and there is no possibility to add ruby with pacman.
Hence, I am not sure if it's OK to recommend it...

**Comment by szorfein** [comment]
I have to test on a recent image. But yeah you don't have a lot of space available.  
Usually you start to install ruby. After that you have to work in /tmp dir because it use ram. So in resume:

1. pacman -S ruby
2. cd /tmp
3. find a way to download getch from this repo (curl or wget https://github.com/szorfein/getch/archive/refs/tags/0.5.0.tar.gz)
4. tar xvf 0.5.0.tar.gz
5. cd in the dir
6. ruby -I lib bin/getch -h

**Comment by oz123** [comment]
Ruby installation failed immediately due to lack of space. But maybe I did something weired with arch linux.
I had a bit more success with voidlinux getting ruby installed and launching the installer. Only to discover nvme device names are not accepted. I got an error when passing `/dev/nvme0`.

**Comment by szorfein** [comment]
Just tested and no problem with the last iso [archlinux-2023.12.01-x86_64.iso](https://mirror.archlinux.ikoula.com/iso/2023.12.01/archlinux-2023.12.01-x86_64.iso).

I could install wget and ruby

    pacman -Sy ruby wget
    ruby -v
    ruby 3.0.6p216 ...

and continious in /tmp for the rest.

    df -h | grep airootfs
    airootfs 256M 84M 173M 33% /

Only take 33% of disk space.

thanks for report, i will add support for ssd disk nvmeX in the day
